### ISSUE TITLE
Include liblsl.csproj into LSLExamples.csproj - error

### ISSUE THREAD

**Issue by AlessiaGiordan** [labstreaminglayer/liblsl-Csharp#16]
Hi,
I'm working with liblsl-Csharp: I followed the instructions of "Using Visual Studio 2019":
- I installed the .NET desktop development pack.
- I added lsl.dll to "liblsl.sln" solution
- I set "Build Action" to "Content" and "Copy to Output Directory" to "Copy if newer" (lsl.dll advanced properties).
- Then I rebuild the solution liblsl.sln without errors
- In the folder Examples I opened "LSLExamples.csproj". Here I found this error: 
**Error	NU1105**:	Could not find project information for '..\liblsl.csproj'. If you are using Visual Studio, this problem can be caused by the project loading being canceled or the project not being part of the current solution, so you need to perform a command line reset. Otherwise, the project file may not be valid or may not include the destinations needed for the restore. 

What I have to do to solve this issue?
Thank you for any advice,

Alessia

**Comment by tstenner** [comment]
Hi,

thanks for the detailed description. I don't have a PC with Visual Studio right now, so I have to guess a bit.
The [solution file](https://github.com/labstreaminglayer/liblsl-Csharp/blob/a1f2a0c7f15d4fbf64f197e58ba027b48d79289b/liblsl.sln) currently has one project for liblsl-Csharp and one project for each example. Could you check that your copy of the liblsl-Csharp repository is up to date?

I can build the `LSLExamples.proj` with the dotnet CLI, but Visual Studio might have a different base path. Can you open the project after replacing the path in the project file with `$(ProjectDir)\..\liblsl.csproj`?

**Comment by dmedine** [comment]
I myself have never seen this error before and cannot reproduce it. Is it possible that Visual Studio upgraded your project settings to target newer versions of .NET? I believe that in the repository liblsl targets netstandard2.0 but that the examples target netcoreapp2.0 (which, by the way, now generates a warning since it is so out of date).

**Comment by dmedine** [comment]
Another thing to check (in case you haven't already) is the dependencies in your example projects. Maybe for some reason they are pointing to some incompatible version of the wrapper?

**Comment by AlessiaGiordan** [comment]
Hi,
Thank you for your quick replies. The problem was that I opened the first project that I saw in the folder Examples LSLexamples.csproj (maybe It was an older version?), instead of checking inside each example folder (where as you said there is a specific project for each example). Now It works. Thanks

Alessia
