### ISSUE TITLE
inlet.pull_sample not returning

### ISSUE THREAD

**Issue by donsay** [labstreaminglayer/liblsl-Csharp#21]
I'm writing a VS2019 app in CSharp to listen for LSL messages, using lsl.dll v1.15.2.

I have confirmed that LSL.resolve_stream() is seeing the messages, and I can see the xml data from inlet.info().as_xml().
But when I call inlet.pull_sample(), I can see that the method dll.lsl_pull_sample_str() (in LSL.cs) never returns.  When I call inlet.pull_sample(), I'm passing in a string[] initialized with one element. 

In this app, I can send messages into LSL, and those are the ones being seen by LSL.resolve_stream(), so I think lsl.dll is being recognized by my code.

Thanks.

**Comment by donsay** [comment]
Thanks for responding. Yeah, it doesn't seem like a this is a bug, or it would be popping up all over.
That sample is what I based my code on, but I haven't run the sample, I'll try it tonight.
Here's my test code...'ID' is a string containing the type of message.

```
public void Send (string message)
{
    StreamInfo streamInfo = new StreamInfo("Test", ID, 1, 0, channel_format_t.cf_string, "sample");
    StreamOutlet streamOutlet = new StreamOutlet(streamInfo);
    string[] msg = new string[1] { message };
    streamOutlet.push_sample(msg);

    StreamInfo[] LSLresults = LSL.LSL.resolve_stream("type", ID);
    StreamInlet inlet = new StreamInlet(LSLresults[0]);
    var info = inlet.info().as_xml();
    LSLresults.DisposeArray();
    msg = new string[1];
    double ct = inlet.pull_sample(msg);
}

```
I tried wrapping 'lsl_pull_sample_str()' (LSL.cs) in a try/catch, but no exceptions were seen.
I saw some internal error codes in LSL.cs, how can I trap those?

**Comment by donsay** [comment]
That makes sense. I was in the process of creating a separate Sender app
that will send messages on a periodic basis, once a second to start.
However, when I run that with my app, pull_sample still fires and doesn't
return.

I will try the sample receiver project tomorrow.

**Comment by dmedine** [comment]
Thanks for cleaning up my typo, Chad!

Just a stab in the dark here since the picture didn't show up. When you build ReceiveStringMarkers, did you make sure to add lsl.dll to the project and set its 'Copy to output directory' property to 'Copy if newer'?
